name: Gradle Selenium

on: [workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ['chrome', 'edge']
        instance: [1, 2, 3, 4, 5]

    steps:
      - name : Checkout code
        uses: actions/checkout@v2
      - name : Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
